export function agendaAteg() {
    const datas = [
        {
            eventId: 'D8',
            title: 'Recanto da Onça',
            dateEvent: '2024-01-01',
            location: 'Técnico Giovane Pelanda Vendram',
            produtor: 'Cassiano Rogerio Ribeiro de Assiz',
            grupo: 'Técnico Giovane Pelanda Vendram',
            date:  '2024-01-01',
            status: 'Visita Realizada',
            color: '#F7D308', // Amarelo para o D8
        },
        {
            eventId: 'D10',
            title: 'Recanto da Onça',
            dateEvent: '2024-01-01',
            location: 'Técnico Giovane Pelanda Vendram',
            produtor: 'Sirley Fernandes',
            grupo: 'Técnico Giovane Pelanda Vendram',
            date:  '2024-01-01',
            status: 'Aguardando Visita',
            color: '#D30707', // Vermelho para o D10
        },
    ];
    return datas;
}


export function schedules() {
    const datas = [
        {
            "id": 89,
            "inseminacao_groups_id": 14,
            "inseminacao_groups_property_id": 230,
            "associate_id": 27634,
            "protocol_step": "D0",
            "date": "2024-09-28",
            "time": "06:00:00",
            "visited": 0,
            "group_name": "Tecnico Giovane Pelanda Vendrame - Corte",
            "associate": {
                "id": 27634,
                "id_sisateg": 224207,
                "id_technician": 249579,
                "id_productive_chain": 3,
                "inseminacao_groups_properties_id": null,
                "producer": "Sirley Fernandes",
                "technician": {
                    "id": 249579,
                    "participant_id": null,
                    "document": "07531823942",
                    "name": "Giovane Pelanda Vendrame",
                    "email": "giovane.vendrame@gmail.com",
                    "email_verified_at": null,
                    "status": 1,
                    "grant_access_at": null,
                    "revoke_access_at": null,
                    "created_at": "2023-04-13T18:07:29.000000Z",
                    "updated_at": "2024-07-09T16:00:50.000000Z"
                },
                "property": "Sítio Modelo",
                "productive_chain": {
                    "id": 3,
                    "name": "BOVINOCULTURA DE CORTE",
                    "center_coust": null,
                    "visiting_time": 4,
                    "path": "ATeG_marcas_Corte.png",
                    "status": 1,
                    "created_at": "2022-12-06T22:45:35.000000Z",
                    "updated_at": "2022-12-13T23:34:18.000000Z",
                    "deleted_at": null
                },
                "syndicate": "SINDICATO RURAL DE BRASNORTE",
                "telephone": "66999817436",
                "cellphone": "",
                "latitude": "-12.2492939",
                "longitude": "-57.8724568",
                "status": 1,
                "protocolo": null,
                "diagnosis_gestation": null,
                "step": null,
                "racas": [],
                "schedule": [],
                "address": {
                    "street": "Sítio Modelo-Vila Boa Esperança-Gleba Tibagi",
                    "number": "",
                    "neighborhood": "",
                    "city": "Brasnorte"
                }
            },
            "updated_at": "2024-09-27T21:04:37.000000Z"
        },
        {
            "id": 90,
            "inseminacao_groups_id": 14,
            "inseminacao_groups_property_id": 230,
            "associate_id": 27634,
            "protocol_step": "D8",
            "date": "2024-10-03",
            "time": null,
            "visited": 0,
            "group_name": "Tecnico Giovane Pelanda Vendrame - Corte ATEG",
            "associate": {
                "id": 27634,
                "id_sisateg": 224207,
                "id_technician": 249579,
                "id_productive_chain": 3,
                "inseminacao_groups_properties_id": null,
                "producer": "Sirley Fernandes",
                "technician": {
                    "id": 249579,
                    "participant_id": null,
                    "document": "07531823942",
                    "name": "Giovane Pelanda Vendrame",
                    "email": "giovane.vendrame@gmail.com",
                    "email_verified_at": null,
                    "status": 1,
                    "grant_access_at": null,
                    "revoke_access_at": null,
                    "created_at": "2023-04-13T18:07:29.000000Z",
                    "updated_at": "2024-07-09T16:00:50.000000Z"
                },
                "property": "Sítio Modelo ATEG",
                "productive_chain": {
                    "id": 3,
                    "name": "BOVINOCULTURA DE CORTE",
                    "center_coust": null,
                    "visiting_time": 4,
                    "path": "ATeG_marcas_Corte.png",
                    "status": 1,
                    "created_at": "2022-12-06T22:45:35.000000Z",
                    "updated_at": "2022-12-13T23:34:18.000000Z",
                    "deleted_at": null
                },
                "syndicate": "SINDICATO RURAL DE BRASNORTE",
                "telephone": "66999817436",
                "cellphone": "",
                "latitude": "-15.6175033",
                "longitude": "-56.0917505",
                "status": 1,
                "protocolo": null,
                "diagnosis_gestation": null,
                "step": null,
                "racas": [],
                "schedule": [],
                "address": {
                    "street": "Sítio Modelo-Vila Boa Esperança-Gleba Tibagi",
                    "number": "",
                    "neighborhood": "",
                    "city": "Brasnorte"
                }
            },
            "updated_at": "2024-09-27T21:04:37.000000Z"
        },
        {
            "id": 91,
            "inseminacao_groups_id": 14,
            "inseminacao_groups_property_id": 230,
            "associate_id": 27634,
            "protocol_step": "D10",
            "date": "2024-10-08",
            "time": null,
            "visited": 0,
            "group_name": "Tecnico Giovane Pelanda Vendrame - Corte",
            "associate": {
                "id": 27634,
                "id_sisateg": 224207,
                "id_technician": 249579,
                "id_productive_chain": 3,
                "inseminacao_groups_properties_id": null,
                "producer": "Sirley Fernandes",
                "technician": {
                    "id": 249579,
                    "participant_id": null,
                    "document": "07531823942",
                    "name": "Giovane Pelanda Vendrame",
                    "email": "giovane.vendrame@gmail.com",
                    "email_verified_at": null,
                    "status": 1,
                    "grant_access_at": null,
                    "revoke_access_at": null,
                    "created_at": "2023-04-13T18:07:29.000000Z",
                    "updated_at": "2024-07-09T16:00:50.000000Z"
                },
                "property": "Sítio Modelo",
                "productive_chain": {
                    "id": 3,
                    "name": "BOVINOCULTURA DE CORTE",
                    "center_coust": null,
                    "visiting_time": 4,
                    "path": "ATeG_marcas_Corte.png",
                    "status": 1,
                    "created_at": "2022-12-06T22:45:35.000000Z",
                    "updated_at": "2022-12-13T23:34:18.000000Z",
                    "deleted_at": null
                },
                "syndicate": "SINDICATO RURAL DE BRASNORTE",
                "telephone": "66999817436",
                "cellphone": "",
                "latitude": "-12.2492939",
                "longitude": "-57.8724568",
                "status": 1,
                "protocolo": null,
                "diagnosis_gestation": null,
                "step": null,
                "racas": [],
                "schedule": [],
                "address": {
                    "street": "Sítio Modelo-Vila Boa Esperança-Gleba Tibagi",
                    "number": "",
                    "neighborhood": "",
                    "city": "Brasnorte"
                }
            },
            "updated_at": "2024-09-27T21:04:37.000000Z"
        },
        {
            "id": 92,
            "inseminacao_groups_id": 14,
            "inseminacao_groups_property_id": 230,
            "associate_id": 27634,
            "protocol_step": "DG",
            "date": "2024-11-02",
            "time": null,
            "visited": 0,
            "group_name": "Tecnico Giovane Pelanda Vendrame - Corte",
            "associate": {
                "id": 27634,
                "id_sisateg": 224207,
                "id_technician": 249579,
                "id_productive_chain": 3,
                "inseminacao_groups_properties_id": null,
                "producer": "Sirley Fernandes",
                "technician": {
                    "id": 249579,
                    "participant_id": null,
                    "document": "07531823942",
                    "name": "Giovane Pelanda Vendrame",
                    "email": "giovane.vendrame@gmail.com",
                    "email_verified_at": null,
                    "status": 1,
                    "grant_access_at": null,
                    "revoke_access_at": null,
                    "created_at": "2023-04-13T18:07:29.000000Z",
                    "updated_at": "2024-07-09T16:00:50.000000Z"
                },
                "property": "Sítio Modelo",
                "productive_chain": {
                    "id": 3,
                    "name": "BOVINOCULTURA DE CORTE",
                    "center_coust": null,
                    "visiting_time": 4,
                    "path": "ATeG_marcas_Corte.png",
                    "status": 1,
                    "created_at": "2022-12-06T22:45:35.000000Z",
                    "updated_at": "2022-12-13T23:34:18.000000Z",
                    "deleted_at": null
                },
                "syndicate": "SINDICATO RURAL DE BRASNORTE",
                "telephone": "66999817436",
                "cellphone": "",
                "latitude": "-12.2492939",
                "longitude": "-57.8724568",
                "status": 1,
                "protocolo": null,
                "diagnosis_gestation": null,
                "step": null,
                "racas": [],
                "schedule": [],
                "address": {
                    "street": "Sítio Modelo-Vila Boa Esperança-Gleba Tibagi",
                    "number": "",
                    "neighborhood": "",
                    "city": "Brasnorte"
                }
            },
            "updated_at": "2024-09-27T21:04:37.000000Z"
        },
        {
            "id": 93,
            "inseminacao_groups_id": 14,
            "inseminacao_groups_property_id": 231,
            "associate_id": 24932,
            "protocol_step": "D0",
            "date": "2024-10-01",
            "time": "03:00:00",
            "visited": 0,
            "group_name": "Tecnico Giovane Pelanda Vendrame - Corte",
            "associate": {
                "id": 24932,
                "id_sisateg": 237864,
                "id_technician": 249579,
                "id_productive_chain": 3,
                "inseminacao_groups_properties_id": null,
                "producer": "Tiago Gonçalves de Carvalho",
                "technician": {
                    "id": 249579,
                    "participant_id": null,
                    "document": "07531823942",
                    "name": "Giovane Pelanda Vendrame",
                    "email": "giovane.vendrame@gmail.com",
                    "email_verified_at": null,
                    "status": 1,
                    "grant_access_at": null,
                    "revoke_access_at": null,
                    "created_at": "2023-04-13T18:07:29.000000Z",
                    "updated_at": "2024-07-09T16:00:50.000000Z"
                },
                "property": "Sítio Boa Vista",
                "productive_chain": {
                    "id": 3,
                    "name": "BOVINOCULTURA DE CORTE",
                    "center_coust": null,
                    "visiting_time": 4,
                    "path": "ATeG_marcas_Corte.png",
                    "status": 1,
                    "created_at": "2022-12-06T22:45:35.000000Z",
                    "updated_at": "2022-12-13T23:34:18.000000Z",
                    "deleted_at": null
                },
                "syndicate": "SINDICATO RURAL DE BRASNORTE",
                "telephone": "65999250484",
                "cellphone": "",
                "latitude": "-12.33022354",
                "longitude": "-57.86934455",
                "status": 1,
                "protocolo": null,
                "diagnosis_gestation": null,
                "step": null,
                "racas": [],
                "schedule": [],
                "address": {
                    "street": "Gleba Tibagi, Vila Boa Esperança, Sítio Boa Vista",
                    "number": "",
                    "neighborhood": "",
                    "city": "Brasnorte"
                }
            },
            "updated_at": "2024-09-30T17:51:27.000000Z"
        },
        {
            "id": 94,
            "inseminacao_groups_id": 14,
            "inseminacao_groups_property_id": 231,
            "associate_id": 24932,
            "protocol_step": "D8",
            "date": "2024-10-09",
            "time": null,
            "visited": 0,
            "group_name": "Tecnico Giovane Pelanda Vendrame - Corte",
            "associate": {
                "id": 24932,
                "id_sisateg": 237864,
                "id_technician": 249579,
                "id_productive_chain": 3,
                "inseminacao_groups_properties_id": null,
                "producer": "Tiago Gonçalves de Carvalho",
                "technician": {
                    "id": 249579,
                    "participant_id": null,
                    "document": "07531823942",
                    "name": "Giovane Pelanda Vendrame",
                    "email": "giovane.vendrame@gmail.com",
                    "email_verified_at": null,
                    "status": 1,
                    "grant_access_at": null,
                    "revoke_access_at": null,
                    "created_at": "2023-04-13T18:07:29.000000Z",
                    "updated_at": "2024-07-09T16:00:50.000000Z"
                },
                "property": "Sítio Boa Vista",
                "productive_chain": {
                    "id": 3,
                    "name": "BOVINOCULTURA DE CORTE",
                    "center_coust": null,
                    "visiting_time": 4,
                    "path": "ATeG_marcas_Corte.png",
                    "status": 1,
                    "created_at": "2022-12-06T22:45:35.000000Z",
                    "updated_at": "2022-12-13T23:34:18.000000Z",
                    "deleted_at": null
                },
                "syndicate": "SINDICATO RURAL DE BRASNORTE",
                "telephone": "65999250484",
                "cellphone": "",
                "latitude": "-12.33022354",
                "longitude": "-57.86934455",
                "status": 1,
                "protocolo": null,
                "diagnosis_gestation": null,
                "step": null,
                "racas": [],
                "schedule": [],
                "address": {
                    "street": "Gleba Tibagi, Vila Boa Esperança, Sítio Boa Vista",
                    "number": "",
                    "neighborhood": "",
                    "city": "Brasnorte"
                }
            },
            "updated_at": "2024-09-30T17:51:27.000000Z"
        },
        {
            "id": 95,
            "inseminacao_groups_id": 14,
            "inseminacao_groups_property_id": 231,
            "associate_id": 24932,
            "protocol_step": "D10",
            "date": "2024-10-11",
            "time": null,
            "visited": 0,
            "group_name": "Tecnico Giovane Pelanda Vendrame - Corte",
            "associate": {
                "id": 24932,
                "id_sisateg": 237864,
                "id_technician": 249579,
                "id_productive_chain": 3,
                "inseminacao_groups_properties_id": null,
                "producer": "Tiago Gonçalves de Carvalho",
                "technician": {
                    "id": 249579,
                    "participant_id": null,
                    "document": "07531823942",
                    "name": "Giovane Pelanda Vendrame",
                    "email": "giovane.vendrame@gmail.com",
                    "email_verified_at": null,
                    "status": 1,
                    "grant_access_at": null,
                    "revoke_access_at": null,
                    "created_at": "2023-04-13T18:07:29.000000Z",
                    "updated_at": "2024-07-09T16:00:50.000000Z"
                },
                "property": "Sítio Boa Vista",
                "productive_chain": {
                    "id": 3,
                    "name": "BOVINOCULTURA DE CORTE",
                    "center_coust": null,
                    "visiting_time": 4,
                    "path": "ATeG_marcas_Corte.png",
                    "status": 1,
                    "created_at": "2022-12-06T22:45:35.000000Z",
                    "updated_at": "2022-12-13T23:34:18.000000Z",
                    "deleted_at": null
                },
                "syndicate": "SINDICATO RURAL DE BRASNORTE",
                "telephone": "65999250484",
                "cellphone": "",
                "latitude": "-12.33022354",
                "longitude": "-57.86934455",
                "status": 1,
                "protocolo": null,
                "diagnosis_gestation": null,
                "step": null,
                "racas": [],
                "schedule": [],
                "address": {
                    "street": "Gleba Tibagi, Vila Boa Esperança, Sítio Boa Vista",
                    "number": "",
                    "neighborhood": "",
                    "city": "Brasnorte"
                }
            },
            "updated_at": "2024-09-30T17:51:27.000000Z"
        },
        {
            "id": 96,
            "inseminacao_groups_id": 14,
            "inseminacao_groups_property_id": 231,
            "associate_id": 24932,
            "protocol_step": "DG",
            "date": "2024-11-05",
            "time": null,
            "visited": 0,
            "group_name": "Tecnico Giovane Pelanda Vendrame - Corte",
            "associate": {
                "id": 24932,
                "id_sisateg": 237864,
                "id_technician": 249579,
                "id_productive_chain": 3,
                "inseminacao_groups_properties_id": null,
                "producer": "Tiago Gonçalves de Carvalho",
                "technician": {
                    "id": 249579,
                    "participant_id": null,
                    "document": "07531823942",
                    "name": "Giovane Pelanda Vendrame",
                    "email": "giovane.vendrame@gmail.com",
                    "email_verified_at": null,
                    "status": 1,
                    "grant_access_at": null,
                    "revoke_access_at": null,
                    "created_at": "2023-04-13T18:07:29.000000Z",
                    "updated_at": "2024-07-09T16:00:50.000000Z"
                },
                "property": "Sítio Boa Vista",
                "productive_chain": {
                    "id": 3,
                    "name": "BOVINOCULTURA DE CORTE",
                    "center_coust": null,
                    "visiting_time": 4,
                    "path": "ATeG_marcas_Corte.png",
                    "status": 1,
                    "created_at": "2022-12-06T22:45:35.000000Z",
                    "updated_at": "2022-12-13T23:34:18.000000Z",
                    "deleted_at": null
                },
                "syndicate": "SINDICATO RURAL DE BRASNORTE",
                "telephone": "65999250484",
                "cellphone": "",
                "latitude": "-12.33022354",
                "longitude": "-57.86934455",
                "status": 1,
                "protocolo": null,
                "diagnosis_gestation": null,
                "step": null,
                "racas": [],
                "schedule": [],
                "address": {
                    "street": "Gleba Tibagi, Vila Boa Esperança, Sítio Boa Vista",
                    "number": "",
                    "neighborhood": "",
                    "city": "Brasnorte"
                }
            },
            "updated_at": "2024-09-30T17:51:27.000000Z"
        },
        {
            "id": 97,
            "inseminacao_groups_id": 14,
            "inseminacao_groups_property_id": 232,
            "associate_id": 22595,
            "protocol_step": "D0",
            "date": "2024-10-02",
            "time": "08:00:00",
            "visited": 0,
            "group_name": "Tecnico Giovane Pelanda Vendrame - Corte",
            "associate": {
                "id": 22595,
                "id_sisateg": 237853,
                "id_technician": 249579,
                "id_productive_chain": 3,
                "inseminacao_groups_properties_id": null,
                "producer": "Wilson Dario Bracht",
                "technician": {
                    "id": 249579,
                    "participant_id": null,
                    "document": "07531823942",
                    "name": "Giovane Pelanda Vendrame",
                    "email": "giovane.vendrame@gmail.com",
                    "email_verified_at": null,
                    "status": 1,
                    "grant_access_at": null,
                    "revoke_access_at": null,
                    "created_at": "2023-04-13T18:07:29.000000Z",
                    "updated_at": "2024-07-09T16:00:50.000000Z"
                },
                "property": "Sítio Família Bracht",
                "productive_chain": {
                    "id": 3,
                    "name": "BOVINOCULTURA DE CORTE",
                    "center_coust": null,
                    "visiting_time": 4,
                    "path": "ATeG_marcas_Corte.png",
                    "status": 1,
                    "created_at": "2022-12-06T22:45:35.000000Z",
                    "updated_at": "2022-12-13T23:34:18.000000Z",
                    "deleted_at": null
                },
                "syndicate": "SINDICATO RURAL DE BRASNORTE",
                "telephone": "66999133983",
                "cellphone": "",
                "latitude": "-12.4532511",
                "longitude": "-57.74229478",
                "status": 1,
                "protocolo": null,
                "diagnosis_gestation": null,
                "step": null,
                "racas": [],
                "schedule": [],
                "address": {
                    "street": "Gleba Tibagi, Comunidade Santa Luzia, Sítio Família Bracht",
                    "number": "",
                    "neighborhood": "",
                    "city": "Brasnorte"
                }
            },
            "updated_at": "2024-09-30T20:43:29.000000Z"
        },
        {
            "id": 98,
            "inseminacao_groups_id": 14,
            "inseminacao_groups_property_id": 232,
            "associate_id": 22595,
            "protocol_step": "D8",
            "date": "2024-10-10",
            "time": "08:00:00",
            "visited": 0,
            "group_name": "Tecnico Giovane Pelanda Vendrame - Corte",
            "associate": {
                "id": 22595,
                "id_sisateg": 237853,
                "id_technician": 249579,
                "id_productive_chain": 3,
                "inseminacao_groups_properties_id": null,
                "producer": "Wilson Dario Bracht",
                "technician": {
                    "id": 249579,
                    "participant_id": null,
                    "document": "07531823942",
                    "name": "Giovane Pelanda Vendrame",
                    "email": "giovane.vendrame@gmail.com",
                    "email_verified_at": null,
                    "status": 1,
                    "grant_access_at": null,
                    "revoke_access_at": null,
                    "created_at": "2023-04-13T18:07:29.000000Z",
                    "updated_at": "2024-07-09T16:00:50.000000Z"
                },
                "property": "Sítio Família Bracht",
                "productive_chain": {
                    "id": 3,
                    "name": "BOVINOCULTURA DE CORTE",
                    "center_coust": null,
                    "visiting_time": 4,
                    "path": "ATeG_marcas_Corte.png",
                    "status": 1,
                    "created_at": "2022-12-06T22:45:35.000000Z",
                    "updated_at": "2022-12-13T23:34:18.000000Z",
                    "deleted_at": null
                },
                "syndicate": "SINDICATO RURAL DE BRASNORTE",
                "telephone": "66999133983",
                "cellphone": "",
                "latitude": "-12.4532511",
                "longitude": "-57.74229478",
                "status": 1,
                "protocolo": null,
                "diagnosis_gestation": null,
                "step": null,
                "racas": [],
                "schedule": [],
                "address": {
                    "street": "Gleba Tibagi, Comunidade Santa Luzia, Sítio Família Bracht",
                    "number": "",
                    "neighborhood": "",
                    "city": "Brasnorte"
                }
            },
            "updated_at": "2024-09-30T20:43:29.000000Z"
        },
        {
            "id": 99,
            "inseminacao_groups_id": 14,
            "inseminacao_groups_property_id": 232,
            "associate_id": 22595,
            "protocol_step": "D10",
            "date": "2024-10-12",
            "time": "08:00:00",
            "visited": 0,
            "group_name": "Tecnico Giovane Pelanda Vendrame - Corte",
            "associate": {
                "id": 22595,
                "id_sisateg": 237853,
                "id_technician": 249579,
                "id_productive_chain": 3,
                "inseminacao_groups_properties_id": null,
                "producer": "Wilson Dario Bracht",
                "technician": {
                    "id": 249579,
                    "participant_id": null,
                    "document": "07531823942",
                    "name": "Giovane Pelanda Vendrame",
                    "email": "giovane.vendrame@gmail.com",
                    "email_verified_at": null,
                    "status": 1,
                    "grant_access_at": null,
                    "revoke_access_at": null,
                    "created_at": "2023-04-13T18:07:29.000000Z",
                    "updated_at": "2024-07-09T16:00:50.000000Z"
                },
                "property": "Sítio Família Bracht",
                "productive_chain": {
                    "id": 3,
                    "name": "BOVINOCULTURA DE CORTE",
                    "center_coust": null,
                    "visiting_time": 4,
                    "path": "ATeG_marcas_Corte.png",
                    "status": 1,
                    "created_at": "2022-12-06T22:45:35.000000Z",
                    "updated_at": "2022-12-13T23:34:18.000000Z",
                    "deleted_at": null
                },
                "syndicate": "SINDICATO RURAL DE BRASNORTE",
                "telephone": "66999133983",
                "cellphone": "",
                "latitude": "-12.4532511",
                "longitude": "-57.74229478",
                "status": 1,
                "protocolo": null,
                "diagnosis_gestation": null,
                "step": null,
                "racas": [],
                "schedule": [],
                "address": {
                    "street": "Gleba Tibagi, Comunidade Santa Luzia, Sítio Família Bracht",
                    "number": "",
                    "neighborhood": "",
                    "city": "Brasnorte"
                }
            },
            "updated_at": "2024-09-30T20:43:29.000000Z"
        },
        {
            "id": 100,
            "inseminacao_groups_id": 14,
            "inseminacao_groups_property_id": 232,
            "associate_id": 22595,
            "protocol_step": "DG",
            "date": "2024-11-06",
            "time": "08:00:00",
            "visited": 0,
            "group_name": "Tecnico Giovane Pelanda Vendrame - Corte",
            "associate": {
                "id": 22595,
                "id_sisateg": 237853,
                "id_technician": 249579,
                "id_productive_chain": 3,
                "inseminacao_groups_properties_id": null,
                "producer": "Wilson Dario Bracht",
                "technician": {
                    "id": 249579,
                    "participant_id": null,
                    "document": "07531823942",
                    "name": "Giovane Pelanda Vendrame",
                    "email": "giovane.vendrame@gmail.com",
                    "email_verified_at": null,
                    "status": 1,
                    "grant_access_at": null,
                    "revoke_access_at": null,
                    "created_at": "2023-04-13T18:07:29.000000Z",
                    "updated_at": "2024-07-09T16:00:50.000000Z"
                },
                "property": "Sítio Família Bracht",
                "productive_chain": {
                    "id": 3,
                    "name": "BOVINOCULTURA DE CORTE",
                    "center_coust": null,
                    "visiting_time": 4,
                    "path": "ATeG_marcas_Corte.png",
                    "status": 1,
                    "created_at": "2022-12-06T22:45:35.000000Z",
                    "updated_at": "2022-12-13T23:34:18.000000Z",
                    "deleted_at": null
                },
                "syndicate": "SINDICATO RURAL DE BRASNORTE",
                "telephone": "66999133983",
                "cellphone": "",
                "latitude": "-12.4532511",
                "longitude": "-57.74229478",
                "status": 1,
                "protocolo": null,
                "diagnosis_gestation": null,
                "step": null,
                "racas": [],
                "schedule": [],
                "address": {
                    "street": "Gleba Tibagi, Comunidade Santa Luzia, Sítio Família Bracht",
                    "number": "",
                    "neighborhood": "",
                    "city": "Brasnorte"
                }
            },
            "updated_at": "2024-09-30T20:43:29.000000Z"
        },
        {
            "id": 101,
            "inseminacao_groups_id": 15,
            "inseminacao_groups_property_id": 233,
            "associate_id": 24319,
            "protocol_step": "D0",
            "date": "2024-11-01",
            "time": "03:00:00",
            "visited": 0,
            "group_name": "Tecnico Gustavo Kuhne Andrade Cidin - Corte",
            "associate": {
                "id": 24319,
                "id_sisateg": 171659,
                "id_technician": 249582,
                "id_productive_chain": 3,
                "inseminacao_groups_properties_id": null,
                "producer": "Anderson Douglas Thibes de Oliveira",
                "technician": {
                    "id": 249582,
                    "participant_id": null,
                    "document": "03989075101",
                    "name": "Gustavo Kuhne Andrade Cidin",
                    "email": "gustavocidin@gmail.com",
                    "email_verified_at": null,
                    "status": 1,
                    "grant_access_at": null,
                    "revoke_access_at": null,
                    "created_at": "2023-04-13T18:10:04.000000Z",
                    "updated_at": "2024-07-09T16:00:51.000000Z"
                },
                "property": "Sitio Nossa Senhora do Carmo",
                "productive_chain": {
                    "id": 3,
                    "name": "BOVINOCULTURA DE CORTE",
                    "center_coust": null,
                    "visiting_time": 4,
                    "path": "ATeG_marcas_Corte.png",
                    "status": 1,
                    "created_at": "2022-12-06T22:45:35.000000Z",
                    "updated_at": "2022-12-13T23:34:18.000000Z",
                    "deleted_at": null
                },
                "syndicate": "SINDICATO RURAL DE JUINA",
                "telephone": "6696939722",
                "cellphone": "",
                "latitude": "-11.352304775901",
                "longitude": "-58.888623186611",
                "status": 1,
                "protocolo": null,
                "diagnosis_gestation": null,
                "step": null,
                "racas": [],
                "schedule": [],
                "address": {
                    "street": "Linha Flor da Serra, Seção H",
                    "number": "",
                    "neighborhood": "",
                    "city": "Juína"
                }
            },
            "updated_at": "2024-10-01T21:01:43.000000Z"
        },
        {
            "id": 102,
            "inseminacao_groups_id": 15,
            "inseminacao_groups_property_id": 233,
            "associate_id": 24319,
            "protocol_step": "D8",
            "date": "2024-11-09",
            "time": "03:00:00",
            "visited": 0,
            "group_name": "Tecnico Gustavo Kuhne Andrade Cidin - Corte",
            "associate": {
                "id": 24319,
                "id_sisateg": 171659,
                "id_technician": 249582,
                "id_productive_chain": 3,
                "inseminacao_groups_properties_id": null,
                "producer": "Anderson Douglas Thibes de Oliveira",
                "technician": {
                    "id": 249582,
                    "participant_id": null,
                    "document": "03989075101",
                    "name": "Gustavo Kuhne Andrade Cidin",
                    "email": "gustavocidin@gmail.com",
                    "email_verified_at": null,
                    "status": 1,
                    "grant_access_at": null,
                    "revoke_access_at": null,
                    "created_at": "2023-04-13T18:10:04.000000Z",
                    "updated_at": "2024-07-09T16:00:51.000000Z"
                },
                "property": "Sitio Nossa Senhora do Carmo",
                "productive_chain": {
                    "id": 3,
                    "name": "BOVINOCULTURA DE CORTE",
                    "center_coust": null,
                    "visiting_time": 4,
                    "path": "ATeG_marcas_Corte.png",
                    "status": 1,
                    "created_at": "2022-12-06T22:45:35.000000Z",
                    "updated_at": "2022-12-13T23:34:18.000000Z",
                    "deleted_at": null
                },
                "syndicate": "SINDICATO RURAL DE JUINA",
                "telephone": "6696939722",
                "cellphone": "",
                "latitude": "-11.352304775901",
                "longitude": "-58.888623186611",
                "status": 1,
                "protocolo": null,
                "diagnosis_gestation": null,
                "step": null,
                "racas": [],
                "schedule": [],
                "address": {
                    "street": "Linha Flor da Serra, Seção H",
                    "number": "",
                    "neighborhood": "",
                    "city": "Juína"
                }
            },
            "updated_at": "2024-10-01T21:01:43.000000Z"
        },
        {
            "id": 103,
            "inseminacao_groups_id": 15,
            "inseminacao_groups_property_id": 233,
            "associate_id": 24319,
            "protocol_step": "D10",
            "date": "2024-11-11",
            "time": "03:00:00",
            "visited": 0,
            "group_name": "Tecnico Gustavo Kuhne Andrade Cidin - Corte",
            "associate": {
                "id": 24319,
                "id_sisateg": 171659,
                "id_technician": 249582,
                "id_productive_chain": 3,
                "inseminacao_groups_properties_id": null,
                "producer": "Anderson Douglas Thibes de Oliveira",
                "technician": {
                    "id": 249582,
                    "participant_id": null,
                    "document": "03989075101",
                    "name": "Gustavo Kuhne Andrade Cidin",
                    "email": "gustavocidin@gmail.com",
                    "email_verified_at": null,
                    "status": 1,
                    "grant_access_at": null,
                    "revoke_access_at": null,
                    "created_at": "2023-04-13T18:10:04.000000Z",
                    "updated_at": "2024-07-09T16:00:51.000000Z"
                },
                "property": "Sitio Nossa Senhora do Carmo",
                "productive_chain": {
                    "id": 3,
                    "name": "BOVINOCULTURA DE CORTE",
                    "center_coust": null,
                    "visiting_time": 4,
                    "path": "ATeG_marcas_Corte.png",
                    "status": 1,
                    "created_at": "2022-12-06T22:45:35.000000Z",
                    "updated_at": "2022-12-13T23:34:18.000000Z",
                    "deleted_at": null
                },
                "syndicate": "SINDICATO RURAL DE JUINA",
                "telephone": "6696939722",
                "cellphone": "",
                "latitude": "-11.352304775901",
                "longitude": "-58.888623186611",
                "status": 1,
                "protocolo": null,
                "diagnosis_gestation": null,
                "step": null,
                "racas": [],
                "schedule": [],
                "address": {
                    "street": "Linha Flor da Serra, Seção H",
                    "number": "",
                    "neighborhood": "",
                    "city": "Juína"
                }
            },
            "updated_at": "2024-10-01T21:01:43.000000Z"
        },
        {
            "id": 104,
            "inseminacao_groups_id": 15,
            "inseminacao_groups_property_id": 233,
            "associate_id": 24319,
            "protocol_step": "DG",
            "date": "2024-12-01",
            "time": "03:00:00",
            "visited": 0,
            "group_name": "Tecnico Gustavo Kuhne Andrade Cidin - Corte",
            "associate": {
                "id": 24319,
                "id_sisateg": 171659,
                "id_technician": 249582,
                "id_productive_chain": 3,
                "inseminacao_groups_properties_id": null,
                "producer": "Anderson Douglas Thibes de Oliveira",
                "technician": {
                    "id": 249582,
                    "participant_id": null,
                    "document": "03989075101",
                    "name": "Gustavo Kuhne Andrade Cidin",
                    "email": "gustavocidin@gmail.com",
                    "email_verified_at": null,
                    "status": 1,
                    "grant_access_at": null,
                    "revoke_access_at": null,
                    "created_at": "2023-04-13T18:10:04.000000Z",
                    "updated_at": "2024-07-09T16:00:51.000000Z"
                },
                "property": "Sitio Nossa Senhora do Carmo",
                "productive_chain": {
                    "id": 3,
                    "name": "BOVINOCULTURA DE CORTE",
                    "center_coust": null,
                    "visiting_time": 4,
                    "path": "ATeG_marcas_Corte.png",
                    "status": 1,
                    "created_at": "2022-12-06T22:45:35.000000Z",
                    "updated_at": "2022-12-13T23:34:18.000000Z",
                    "deleted_at": null
                },
                "syndicate": "SINDICATO RURAL DE JUINA",
                "telephone": "6696939722",
                "cellphone": "",
                "latitude": "-11.352304775901",
                "longitude": "-58.888623186611",
                "status": 1,
                "protocolo": null,
                "diagnosis_gestation": null,
                "step": null,
                "racas": [],
                "schedule": [],
                "address": {
                    "street": "Linha Flor da Serra, Seção H",
                    "number": "",
                    "neighborhood": "",
                    "city": "Juína"
                }
            },
            "updated_at": "2024-10-01T21:21:55.000000Z"
        },
        {
            "id": 105,
            "inseminacao_groups_id": 15,
            "inseminacao_groups_property_id": 347,
            "associate_id": 23026,
            "protocol_step": "D0",
            "date": "2024-11-01",
            "time": "04:00:00",
            "visited": 0,
            "group_name": "Tecnico Gustavo Kuhne Andrade Cidin - Corte",
            "associate": {
                "id": 23026,
                "id_sisateg": 171779,
                "id_technician": 249582,
                "id_productive_chain": 3,
                "inseminacao_groups_properties_id": null,
                "producer": "Valdeir de Oliveira",
                "technician": {
                    "id": 249582,
                    "participant_id": null,
                    "document": "03989075101",
                    "name": "Gustavo Kuhne Andrade Cidin",
                    "email": "gustavocidin@gmail.com",
                    "email_verified_at": null,
                    "status": 1,
                    "grant_access_at": null,
                    "revoke_access_at": null,
                    "created_at": "2023-04-13T18:10:04.000000Z",
                    "updated_at": "2024-07-09T16:00:51.000000Z"
                },
                "property": "Sitio São Benedito",
                "productive_chain": {
                    "id": 3,
                    "name": "BOVINOCULTURA DE CORTE",
                    "center_coust": null,
                    "visiting_time": 4,
                    "path": "ATeG_marcas_Corte.png",
                    "status": 1,
                    "created_at": "2022-12-06T22:45:35.000000Z",
                    "updated_at": "2022-12-13T23:34:18.000000Z",
                    "deleted_at": null
                },
                "syndicate": "SINDICATO RURAL DE JUINA",
                "telephone": "6692317167",
                "cellphone": "",
                "latitude": "-11.316823",
                "longitude": "-58.89252853",
                "status": 1,
                "protocolo": null,
                "diagnosis_gestation": null,
                "step": null,
                "racas": [],
                "schedule": [],
                "address": {
                    "street": "Linha Flor da Serra, Seção H",
                    "number": "",
                    "neighborhood": "",
                    "city": "Juína"
                }
            },
            "updated_at": "2024-10-01T21:07:55.000000Z"
        },
        {
            "id": 106,
            "inseminacao_groups_id": 15,
            "inseminacao_groups_property_id": 347,
            "associate_id": 23026,
            "protocol_step": "D8",
            "date": "2024-11-09",
            "time": "04:00:00",
            "visited": 0,
            "group_name": "Tecnico Gustavo Kuhne Andrade Cidin - Corte",
            "associate": {
                "id": 23026,
                "id_sisateg": 171779,
                "id_technician": 249582,
                "id_productive_chain": 3,
                "inseminacao_groups_properties_id": null,
                "producer": "Valdeir de Oliveira",
                "technician": {
                    "id": 249582,
                    "participant_id": null,
                    "document": "03989075101",
                    "name": "Gustavo Kuhne Andrade Cidin",
                    "email": "gustavocidin@gmail.com",
                    "email_verified_at": null,
                    "status": 1,
                    "grant_access_at": null,
                    "revoke_access_at": null,
                    "created_at": "2023-04-13T18:10:04.000000Z",
                    "updated_at": "2024-07-09T16:00:51.000000Z"
                },
                "property": "Sitio São Benedito",
                "productive_chain": {
                    "id": 3,
                    "name": "BOVINOCULTURA DE CORTE",
                    "center_coust": null,
                    "visiting_time": 4,
                    "path": "ATeG_marcas_Corte.png",
                    "status": 1,
                    "created_at": "2022-12-06T22:45:35.000000Z",
                    "updated_at": "2022-12-13T23:34:18.000000Z",
                    "deleted_at": null
                },
                "syndicate": "SINDICATO RURAL DE JUINA",
                "telephone": "6692317167",
                "cellphone": "",
                "latitude": "-11.316823",
                "longitude": "-58.89252853",
                "status": 1,
                "protocolo": null,
                "diagnosis_gestation": null,
                "step": null,
                "racas": [],
                "schedule": [],
                "address": {
                    "street": "Linha Flor da Serra, Seção H",
                    "number": "",
                    "neighborhood": "",
                    "city": "Juína"
                }
            },
            "updated_at": "2024-10-01T21:07:55.000000Z"
        },
        {
            "id": 107,
            "inseminacao_groups_id": 15,
            "inseminacao_groups_property_id": 347,
            "associate_id": 23026,
            "protocol_step": "D10",
            "date": "2024-11-11",
            "time": "04:00:00",
            "visited": 0,
            "group_name": "Tecnico Gustavo Kuhne Andrade Cidin - Corte",
            "associate": {
                "id": 23026,
                "id_sisateg": 171779,
                "id_technician": 249582,
                "id_productive_chain": 3,
                "inseminacao_groups_properties_id": null,
                "producer": "Valdeir de Oliveira",
                "technician": {
                    "id": 249582,
                    "participant_id": null,
                    "document": "03989075101",
                    "name": "Gustavo Kuhne Andrade Cidin",
                    "email": "gustavocidin@gmail.com",
                    "email_verified_at": null,
                    "status": 1,
                    "grant_access_at": null,
                    "revoke_access_at": null,
                    "created_at": "2023-04-13T18:10:04.000000Z",
                    "updated_at": "2024-07-09T16:00:51.000000Z"
                },
                "property": "Sitio São Benedito",
                "productive_chain": {
                    "id": 3,
                    "name": "BOVINOCULTURA DE CORTE",
                    "center_coust": null,
                    "visiting_time": 4,
                    "path": "ATeG_marcas_Corte.png",
                    "status": 1,
                    "created_at": "2022-12-06T22:45:35.000000Z",
                    "updated_at": "2022-12-13T23:34:18.000000Z",
                    "deleted_at": null
                },
                "syndicate": "SINDICATO RURAL DE JUINA",
                "telephone": "6692317167",
                "cellphone": "",
                "latitude": "-11.316823",
                "longitude": "-58.89252853",
                "status": 1,
                "protocolo": null,
                "diagnosis_gestation": null,
                "step": null,
                "racas": [],
                "schedule": [],
                "address": {
                    "street": "Linha Flor da Serra, Seção H",
                    "number": "",
                    "neighborhood": "",
                    "city": "Juína"
                }
            },
            "updated_at": "2024-10-01T21:07:55.000000Z"
        },
        {
            "id": 108,
            "inseminacao_groups_id": 15,
            "inseminacao_groups_property_id": 347,
            "associate_id": 23026,
            "protocol_step": "DG",
            "date": "2024-12-01",
            "time": "04:00:00",
            "visited": 0,
            "group_name": "Tecnico Gustavo Kuhne Andrade Cidin - Corte",
            "associate": {
                "id": 23026,
                "id_sisateg": 171779,
                "id_technician": 249582,
                "id_productive_chain": 3,
                "inseminacao_groups_properties_id": null,
                "producer": "Valdeir de Oliveira",
                "technician": {
                    "id": 249582,
                    "participant_id": null,
                    "document": "03989075101",
                    "name": "Gustavo Kuhne Andrade Cidin",
                    "email": "gustavocidin@gmail.com",
                    "email_verified_at": null,
                    "status": 1,
                    "grant_access_at": null,
                    "revoke_access_at": null,
                    "created_at": "2023-04-13T18:10:04.000000Z",
                    "updated_at": "2024-07-09T16:00:51.000000Z"
                },
                "property": "Sitio São Benedito",
                "productive_chain": {
                    "id": 3,
                    "name": "BOVINOCULTURA DE CORTE",
                    "center_coust": null,
                    "visiting_time": 4,
                    "path": "ATeG_marcas_Corte.png",
                    "status": 1,
                    "created_at": "2022-12-06T22:45:35.000000Z",
                    "updated_at": "2022-12-13T23:34:18.000000Z",
                    "deleted_at": null
                },
                "syndicate": "SINDICATO RURAL DE JUINA",
                "telephone": "6692317167",
                "cellphone": "",
                "latitude": "-11.316823",
                "longitude": "-58.89252853",
                "status": 1,
                "protocolo": null,
                "diagnosis_gestation": null,
                "step": null,
                "racas": [],
                "schedule": [],
                "address": {
                    "street": "Linha Flor da Serra, Seção H",
                    "number": "",
                    "neighborhood": "",
                    "city": "Juína"
                }
            },
            "updated_at": "2024-10-01T21:07:55.000000Z"
        }
    ];
    return datas;
}


